4 search results components result
buildo/caprio-FE-training pull request #12
Opened 2020-11-13 16:56 UTC by Viktor-K

**TEST PLAN**

Pagination buttons prev and next, for iteration on results pages and update result lists.

2020-11-13 17:38 UTC, veej requested changes

2020-11-13 17:38 UTC, veej commented on src/components/ResturantCard/ResturantCard.tsx
> +export const ResturantCard = (prop: Business) => (
typo :P
```suggestion
export const RestaurantCard = (prop: Business) => (
```

2020-11-13 17:38 UTC, veej commented on src/components/ResturantCard/ResturantCard.tsx
> +    <a href={`${prop.url}`} target="_blank">
blocks inside an `a` anchor are not so standard. Better to pass an `onClick={() => window.open(prop.url, "_blank") }` handler to the next `View` component

2020-11-13 17:38 UTC, veej commented on src/components/SearchFetch/SearchFetch.tsx
> +    }
Shouldn't this be the inverse? If the page is the last one, you should not increment it

2020-11-13 17:38 UTC, veej commented on src/components/SearchFetch/SearchFetch.tsx
> +      ''
Please, don't render empty strings instead of components. You can both return `null` or write this as:
```suggestion
    curPageIsLast(curPage.page, total) && (
       <Button label={nextLabel} onClick={() => nextPage(curPage.page, total)} />
    )
```

2020-11-13 17:38 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +            <ResturantCard key={business.id} {...business} />
isn't it clearer if you pass only one prop `business={business}` instead of spreading all the fields as props?

2020-11-13 17:46 UTC, Viktor-K commented on src/components/SearchFetch/SearchFetch.tsx
> +    }
sure wrong method extraction not is lost

2020-11-13 17:57 UTC, Viktor-K commented on src/components/SearchResults/SearchResults.tsx
> +            <ResturantCard key={business.id} {...business} />
yes make pros more clear in this way

2020-11-16 08:25 UTC, veej requested changes

2020-11-16 08:25 UTC, veej commented on src/components/SearchFetch/SearchFetch.tsx
> +    if (!curPageIsLast(page, total)) {
⚠️ The implementation of the `curPageIsLast` function is not doing what the name tells. This check was correct based on the current implementation of the function. If you change this condition, you should also change the implementation of the function to match its name (`curPageIsLast` should check that page === lastPage, not page < lastPage)

2020-11-16 09:10 UTC, veej approved these changes

2020-11-16 09:13 UTC, merged