Init App Layout and main components, remove boilerplate code
buildo/caprio-FE-training pull request #7
Opened 2020-11-09 16:22 UTC by Viktor-K

**Test plan** 
See in Home page two main components with flex layout in page

It was defined Home page layout and two main components SearchBar and Search results for only viewing purpose, logical features, and style refinements will be done in the next issues.

2020-11-09 18:19 UTC, veej requested changes
Left a few inline comments. Let me know if something is not clear enough :)

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +class SearchBar extends React.Component {
we transitioned to functional components recently (that is a more recent standard in React), so we prefer to not use classes for the components. Could you please convert all your components into functions?

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +        let tmpVal: string = 'Search Location'
please, never use `let` in your code. The occasions where you'll need to modify a variable are very very few.

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +        const mockPerformSearch = () => console.log('Search with Yelp API')
another suggestion for the future: try to avoid putting temporary code in your PRs.
You could pass empty lambdas defined inline. e.g. `<Input onChange={() => {}} />` (or the equivalent `<Input onChange={constVoid} />`)

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +        const buttonProps = {
I admit I've done this a lot in the past too, but it's way more readable if you pass your props inline in the component instead of defining them far from the component itself.

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +            <View width='100%'
I could be wrong, but `width` should not be needed here. If you're inside a flex column, the children will take all the available width

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +                    <View vAlignContent='center'>
are you using prettier in your project? formatting seems a little bit "unusual" to me.

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +                        <Input label="Location search :"
please, consider localizing every rendered string, so you'll be ready to translate your app in a different language.

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/index.ts
> +import SearchBar from './SearchBar';
another thing that we've stopped doing: no need to create an `index.ts` for every component. It's way easier to import directly from the component's file (and the editor will help you a lot with autocompletion)

2020-11-09 18:19 UTC, veej commented on src/components/SearchBar/searchbar.scss
> +.search-bar {
avoid creating empty classes if you don't need them.

2020-11-09 18:19 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +                pipe(
here the pipe is completely useless. You can `map` over `mockList` directly

2020-11-09 18:19 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +                        items.map(name => <View
again a very strange formatting. Please configure prettier and set "format on save" in your editor

2020-11-09 18:19 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +                            width='100%'>  - {name}
width is not required if not in very particular cases. Do you really need it here?

2020-11-09 18:19 UTC, veej commented on src/model/index.ts
> +      return 'detail';
again, this is something you could add later when you need it

2020-11-10 08:37 UTC, Viktor-K commented on src/components/SearchBar/SearchBar.tsx
> +class SearchBar extends React.Component {
Ok it makes absolute sense, I will use only the FC for future

2020-11-10 08:40 UTC, Viktor-K commented on src/components/SearchResults/SearchResults.tsx
> +                        items.map(name => <View
Yes currently my prettier was not work properly in my IDE, I'have configure it again correctly

2020-11-10 08:42 UTC, Viktor-K commented on src/model/index.ts
> +      return 'detail';
Sure now I'm coming to doing changes more clear and focused only ISSUE scope.

2020-11-10 09:21 UTC, veej requested changes
We're almost good to go!
I left a few (minor) suggestions inline about coding style + a change request for FlexView (in general, using flex you shouldn't need to specify percentages, but you should let the flexbox adapt according to the available space).

2020-11-10 09:21 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +const SearchBar: React.FC = () => {
Could simply be like this:
```suggestion
export function SearchBar() {
```

2020-11-10 09:21 UTC, veej commented on src/components/SearchBar/SearchBar.tsx
> +      {
unneeded curly braces

2020-11-10 09:21 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +    <View className="search-results" column hAlignContent={'center'}>
```suggestion
    <View className="search-results" column hAlignContent="center">
```

2020-11-10 09:21 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +        <View className="result-item" hAlignContent={'center'}>
```suggestion
        <View className="result-item" hAlignContent="center">
```

2020-11-10 09:21 UTC, veej commented on src/components/SearchResults/SearchResults.tsx
> +const SearchResults: React.FC = () => {
```suggestion
export function SearchResults() {
```

2020-11-10 09:21 UTC, veej commented on src/components/App/App.tsx
> +        <View style={{ height: '60%' }}>
Why are you setting the height to 60%?
If you add a `grow` prop to the View, this part should be able to take all the available space left under the Header + SearchBar.

2020-11-10 09:34 UTC, Viktor-K commented on src/components/SearchBar/SearchBar.tsx
> +      {
Sure I had noticed this too late

2020-11-10 09:57 UTC, Viktor-K commented on src/components/App/App.tsx
> +        <View style={{ height: '60%' }}>
In the principle, I wanna add some footer in the page layout, so I set height with perc. to left a visible space, but for the moment I'll remove that and use grow to use all space left on the page.

2020-11-10 10:16 UTC, veej commented on src/components/App/App.tsx
> +        <View column hAlignContent="center" grow>
Making both the views `grow`, every view will take half of the screen's height. Is this what you wanted to do?
I would expect the header+search bar with a fixed height and the results grow to take all the remaining space
(but if it was your intention to split the screen in half, feel free to ignore my comment, I'm not interested in getting into UI decisions)

2020-11-10 10:17 UTC, veej approved these changes
Just another clarification comment, but I think we're ready to merge this 🌮

2020-11-10 10:23 UTC, merged