5 yelp api integration search
buildo/caprio-FE-training pull request #9
Opened 2020-11-12 15:10 UTC by Viktor-K

**Test Plan**

Show subset data comes from Yelp API, handle Yelp API errors and show UI message for invalid searched name.

<img width="1771" alt="Screenshot 2020-11-12 at 16 08 49" src="https://user-images.githubusercontent.com/5895397/98957416-769b0d00-2501-11eb-8a67-732aa3543d5a.png">

<img width="1770" alt="Screenshot 2020-11-12 at 16 08 37" src="https://user-images.githubusercontent.com/5895397/98957517-90d4eb00-2501-11eb-9a5b-cc241b9fb907.png">

2020-11-12 16:32 UTC, veej requested changes
Code is (almost) good. Left a few comments inline as usual.
Quite a big PR though. For the future PRs, consider splitting your work into even smaller PRs

2020-11-12 16:32 UTC, veej commented on src/API/API.ts
> +) => taskEither.TaskEither<AppErrors, YelpAPIResponseT> = res => {
minor: just as a guideline we're following on UCZ, we decided to import the ADT (in this case capital `TaskEither`) directly from the specific file (in this case `import { TaskEither } from "fp-ts/TaskEither";`) and use the lowercase `taskEither` (`import { taskEither } from "fp-ts";`) only for the "operations" on the ADT (like map/flatMap/fold/...).
In this way, you can avoid the repetitive `taskEither.TaskEither` for the type.

2020-11-12 16:32 UTC, veej commented on src/components/ErrorMsg/ErrorMsg.tsx
> +    error.code ? `YelpApiErrorCode.${error.code}` : 'YelpApiErrorCode.GENERIC';
according to your codec, `error.code` can't be null/undefined. Can you receive an empty string as a code?

2020-11-12 16:32 UTC, veej commented on src/components/ErrorMsg/ErrorMsg.tsx
> +    );
this is really really strange. What are you trying to accomplish here?
Your `content.type` is a finite set of error types. If you define `errTypeMapper` as a `Record`, the type system will guarantee you always have an element for every error type and you won't need to use that `reduce` on the defined error types

2020-11-12 16:32 UTC, veej commented on src/components/ErrorMsg/ErrorMsg.tsx
> +  return <View className="message-container animate-msg">{renderErrMsg()}</View>;
```suggestion
  return <View className={cx("message-container", "animate-msg")}>{renderErrMsg()}</View>;
```

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +import * as QR from 'avenger/lib/QueryResult';
pedantic comment:
```suggestion
import * as queryResult from 'avenger/lib/QueryResult';
```

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +// import LoadingSpinner from '../LoadingSpinner/LoadingSpinner';
leftover?

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +  const performSearch = async (location: string, range: number) =>
why do you need the `async` here?

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +          (error: AppErrors) => (
you shouldn't need to specify the type here. Avoid unneeded types

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +              <SearchResults />
Is this `SearchResult` still mocked?

2020-11-12 16:32 UTC, veej commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +  const provideResults = () =>
can this `provideResults` be a separate component?
You could move all this logic inside `SearchResults`, and pass the search params as a prop

2020-11-12 16:32 UTC, veej commented on src/config.ts
> +      yelpApiToken:
I don't understand why you put the token in the config if the value is still hardcoded. You should receive this token as an env variable and assign it here

2020-11-12 16:32 UTC, veej commented on src/model/yelp/yelp.tsx
> +export const ResturantLocation = t.partial({
as we discussed earlier, you should be more precise about the result you expect from the API. If you expect some field to be mandatory, you shouldn't use `t.partial` on the whole object.
We're using codecs to ensure that the APIs are compliant with a contract

2020-11-12 16:32 UTC, veej commented on src/model/yelp/yelp.tsx
> +export type YelpAPIErrorResponseT = t.TypeOf<typeof YelpAPIErrorResponse>;
please use the same name for the `io-ts` codec and its type:
```suggestion
export type YelpAPIResponse = t.TypeOf<typeof YelpAPIResponse>;
export type YelpAPIErrorResponse = t.TypeOf<typeof YelpAPIErrorResponse>;
```

2020-11-12 18:01 UTC, Viktor-K commented on src/components/SearchResturantContainer/SearchResturantContainer.tsx
> +              <SearchResults />
Sure not I have delevop a separate component in another branch

2020-11-13 09:31 UTC, veej requested changes
Just a little comment about a useless cast. After that, we'll be ready to merge! 🚀

2020-11-13 09:38 UTC, Viktor-K commented on src/components/ErrorMsg/ErrorMsg.tsx
> +          msg: `${(props.content as YelpError).description}`,
sure unuseful cast,  already inferred by the previous line, I'm overloaded of tasks and I forget something in some parts 😞

2020-11-13 09:42 UTC, veej approved these changes

2020-11-13 09:42 UTC, merged